spring:
    datasource:
        url: jdbc:postgresql://ec2-3-87-180-131.compute-1.amazonaws.com:5432/d7vtng3prf7aj0
        driver-class-name: org.postgresql.Driver
        username: nxgfenjpodocmf
        password: 17b0570a47e62c96303e841c685848cdcf7a1ae2705fd81ec67b22c209661723
        initialization-mode: never
        tomcat:
          test-while-idle: true
          validation-query: SELECT 1
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                default_schema: ${DATABASE_SCHEMA:public}
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                    temp:
                        use_jdbc_metadata_defaults: false
    flyway:
        baseline-on-migrate: true
        locations:
            - classpath:db/migration            
kafka:
  bootstrapAddress: ${KAFKA_URL:localhost:29092}
  