spring:
    datasource:
        url: jdbc:postgresql://ec2-18-211-97-89.compute-1.amazonaws.com:5432/d3emkulf1i3lok
        driver-class-name: org.postgresql.Driver
        username: qijrbxsotpxmcf
        password: 90e66e269b94b0fdc9307830df4fc238cc04c92a3e323ed35e66e626cf99db80
        initialization-mode: never
        tomcat:
          test-while-idle: true
          validation-query: SELECT 1
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                default_schema: ${DATABASE_SCHEMA:public}
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                    temp:
                        use_jdbc_metadata_defaults: false
    flyway:
        baseline-on-migrate: true
        locations:
            - classpath:db/migration
kafka:
  bootstrapAddress: ${KAFKA_URL:localhost:29092}